### ISSUE TITLE
addEventListener / removeEventListener

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/fifo-logger#19]
Currently when creating a FifloLogger we can add a callback `onchange`

https://github.com/cheminfo/fifo-logger/blob/360382052785d3b3fbb3778a5378649501bc1233/src/FifoLogger.ts#L32-L36

We would like to have the possibility to àddEventListener`, `removeEventListener` on an instance of FifoLogger.

It should be compatible with the browser and nodeJS.

@targos What would be the best approach to do this ?

**Comment by targos** [comment]
- Extend `EventTarget`
- Dispatch a `CustomEvent` (or something that extends it)

This is only possible since Node.js 20.

https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events
